USE master

CREATE LOGIN [AppUser]
WITH 
	PASSWORD = 'n4Yg8BeW5aGY2bPn', 
	CHECK_EXPIRATION = OFF,
	CHECK_POLICY = OFF
GO

DROP DATABASE Crm
GO
CREATE DATABASE Crm
GO
USE Crm

CREATE TABLE [dbo].[Customer](
	[Id] INT NOT NULL IDENTITY(1,1)
		CONSTRAINT PK_Customer PRIMARY KEY
	,[EmailAddress] VARBINARY(MAX) NOT NULL
	,[FirstName] VARBINARY(MAX) NOT NULL
	,[MiddleName] VARBINARY(MAX) NULL
	,[LastName] VARBINARY(MAX) NOT NULL
	,[Active] BIT NOT NULL
	,[Password] VARBINARY(MAX) NOT NULL
	,[Created] DATETIMEOFFSET NOT NULL
	,[Modified] DATETIMEOFFSET NOT NULL
)

CREATE USER [AppUser]
FOR LOGIN [AppUser]

ALTER ROLE db_datareader
ADD MEMBER AppUser

ALTER ROLE db_datawriter
ADD MEMBER AppUser

SELECT * FROM [dbo].[Customer]

UPDATE dbo.Customer
SET Active = 1